variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none

stages:
  - all

.job_template: &job_definition
  only:
    - ci_test
  before_script:
    - git submodule update --init --checkout --recursive cosim/import/black-parrot
    - cp -r $CI_RTL_INSTALL_DIR install/
  artifacts:
    when: always
    paths:
      - "cosim/shell-example/verilator/"
      - "cosim/double-shell-example/verilator/"
      - "cosim/shell-example/vcs/"
      - "cosim/double-shell-example/vcs/"
  dependencies: []
  retry:
    max: 2
    when:
      - script_failure

shell-example-verilator:
  <<: *job_definition
  stage: all
  tags:
    - verilator
  script:
    - make -C cosim/shell-example/verilator/ run

shell-example-vcs:
  <<: *job_definition
  stage: all
  tags:
    - vcs
  script:
    - make -C cosim/shell-example/vcs/ run

double-shell-example-verilator:
  <<: *job_definition
  stage: all
  tags:
    - verilator
  script:
    - make -C cosim/double-shell-example/verilator/ run

double-shell-example-vcs:
  <<: *job_definition
  stage: all
  tags:
    - vcs
  script:
    - make -C cosim/double-shell-example/vcs/ run

